// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtfJjKKyysEQsGF7CaOc-2AOXYhuow3w',
    appId: '1:681556435778:web:37d86fe389c801f7325edb',
    messagingSenderId: '681556435778',
    projectId: 'playdate-afca4',
    authDomain: 'playdate-afca4.firebaseapp.com',
    storageBucket: 'playdate-afca4.appspot.com',
    measurementId: 'G-4QB41R2TSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCObV4bP1TR9W8rA1Ui8LWvjd_z-Fl2rY',
    appId: '1:681556435778:android:f02e597d38b5ac90325edb',
    messagingSenderId: '681556435778',
    projectId: 'playdate-afca4',
    storageBucket: 'playdate-afca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1S2o0Kl0MRUqzxGVhaWJHLIk_iDDCpI',
    appId: '1:681556435778:ios:035e5304a4d4f389325edb',
    messagingSenderId: '681556435778',
    projectId: 'playdate-afca4',
    storageBucket: 'playdate-afca4.appspot.com',
    iosBundleId: 'com.example.doggyTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF1S2o0Kl0MRUqzxGVhaWJHLIk_iDDCpI',
    appId: '1:681556435778:ios:133d0ab042b77c69325edb',
    messagingSenderId: '681556435778',
    projectId: 'playdate-afca4',
    storageBucket: 'playdate-afca4.appspot.com',
    iosBundleId: 'com.example.doggyTinder.RunnerTests',
  );
}
